name: PencilEditor
main: com.polypenguin.pencil.Pencil
version: 0.0.2.7
api-version: 1.13
description: Next generation Voxel Editing for Minecraft.
author: [Matthias Kovacic]

commands:
  pencil:
    description: The main pencil command!